name: Build and Download

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Compress Artifacts
        run: tar -czvf artifacts.tar.gz build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-artifacts
          path: artifacts.tar.gz

  download:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: compiled-artifacts
          path: download/

      - name: Extract Artifacts
        run: tar -xzvf download/artifacts.tar.gz
